/*
 * gpio_driver.c
 *
 *  Created on: Dec 21, 2017
 *      Author: a0225962
 */

/*
    MAP_GPIOPinWrite(PIN50_GPIO_BASE, PIN50_GPIO_PIN, PIN50_GPIO_PIN);
    MAP_GPIOPinWrite(PIN62_GPIO_BASE, PIN62_GPIO_PIN, PIN62_GPIO_PIN);
    MAP_GPIOPinWrite(PIN63_GPIO_BASE, PIN63_GPIO_PIN, PIN63_GPIO_PIN);
    MAP_GPIOPinWrite(PIN15_GPIO_BASE, PIN15_GPIO_PIN, PIN15_GPIO_PIN);
    MAP_GPIOPinWrite(PIN18_GPIO_BASE, PIN18_GPIO_PIN, PIN18_GPIO_PIN);


    MAP_GPIOPinWrite(PIN50_GPIO_BASE, PIN50_GPIO_PIN, 0);
    MAP_GPIOPinWrite(PIN62_GPIO_BASE, PIN62_GPIO_PIN, 0);
    MAP_GPIOPinWrite(PIN63_GPIO_BASE, PIN63_GPIO_PIN, 0);
    MAP_GPIOPinWrite(PIN15_GPIO_BASE, PIN15_GPIO_PIN, 0);
    MAP_GPIOPinWrite(PIN18_GPIO_BASE, PIN18_GPIO_PIN, 0);
*/
